version: '3.6'


volumes:
  mongodb_data_06:


services:
  frontend_06:
    container_name: frontend_06
    image: frontend_06:1.0.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8068:80
    depends_on:
      - backend_06
    restart: unless-stopped

  backend_06:
    container_name: backend_06
    image: backend_06:1.0.0
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - URL_MONGO=mongodb://api:docker1234@mongodb_06
    ports:
      - 8067:3000
    depends_on:
      - mongodb_06
    restart: unless-stopped

  mongodb_06:
    container_name: mongodb_06
    image: mongo:latest
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=api
      - MONGO_INITDB_ROOT_PASSWORD=docker1234
    volumes:
      - mongodb_data_06:/data/db
    ports: 
      - 8066:27017
    restart: unless-stopped
